// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using quilombos_api.Data;

#nullable disable

namespace quilombos_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260404161703_AddMoreQuilomboFieldsV3")]
    partial class AddMoreQuilomboFieldsV3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("quilombos_api.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Usuario")
                        .IsUnique();

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SenhaHash = "$2a$11$CUZ9PedF2gUGGMT70Dwg2.tpsXiiT8sjr9LZDRFbedvVhov9mcrtm",
                            Usuario = "admin2026_quilombos"
                        });
                });

            modelBuilder.Entity("quilombos_api.Models.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PostagemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PostagemId");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("quilombos_api.Models.ImagemPostagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeOriginal")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PostagemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PostagemId");

                    b.ToTable("ImagensPostagem");
                });

            modelBuilder.Entity("quilombos_api.Models.Postagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagemHeaderPath")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuilomboId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subtitulo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuilomboId");

                    b.ToTable("Postagens");
                });

            modelBuilder.Entity("quilombos_api.Models.Quilombo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ano")
                        .HasColumnType("TEXT");

                    b.Property<int>("Codigo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cultura")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Familias")
                        .HasColumnType("TEXT");

                    b.Property<string>("Historia")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Municipio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Regiao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Territorio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Quilombos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ano = "Origem no século XIX",
                            Codigo = 1,
                            Cultura = "A cultura aqui é vivida no dia a dia. É na roda de conversa, na farinhada, na festa de santo, na benzeção que a vizinha faz. É no saber de parteira, no conhecimento das ervas, na reza que acalma e no trabalho coletivo da roça. A música é memória, o tambor ecoa, e a culinária traz o gosto do milho, da mandioca e do feijão plantado com as próprias mãos. A ancestralidade não é lembrança, é presença viva que guia os passos de quem anda por essas terras.",
                            Descricao = "O Quilombo Riacho dos Porcos é um território de resistência que pulsa desde os tempos da escravidão.",
                            Familias = "Aproximadamente 40 a 50 famílias",
                            Historia = "O Quilombo Riacho dos Porcos, em Sertânia, Pernambuco, é um território de resistência que pulsa desde os tempos da escravidão. Aqui, a terra foi conquistada com suor e sangue, e cada palmo de chão conta histórias de liberdade. Os mais velhos ainda lembram dos causos contados ao pé do fogo, histórias que atravessaram gerações sem precisar de papel. É da oralidade que nasce a força dessa comunidade, que mantém viva a memória dos que vieram antes e abre caminhos para os que virão.",
                            ImagemUrl = "assets/riacho.png",
                            Municipio = "Sertânia",
                            Nome = "Riacho dos Porcos",
                            Regiao = "Pernambuco",
                            Territorio = "O território não é só chão. É identidade, é pertencimento, é a certeza de que aqui se pode ser quem se é. É o lugar onde os pés se firmam e onde os sonhos se plantam. É onde o trabalho coletivo transforma a terra em sustento e a luta em esperança. Defender esse território é defender a memória dos que vieram antes e o futuro dos que virão depois. É resistir com as mãos na terra e o coração na história."
                        },
                        new
                        {
                            Id = 2,
                            Ano = "Século XIX (formação tradicional)",
                            Codigo = 2,
                            Cultura = "A cultura em Severo se aprende desde cedo. É no respeito aos mais velhos, nas histórias de assombração contadas à noite, no benzimento que cura, no trabalho da roça que alimenta corpo e alma. As tradições se renovam a cada geração, sem perder o fio que conecta le presente ao passado. O som do tambor, o cheiro do fumo de corda, o sabor da rapadura feita no engenho: tudo isso é cultura, é identidade, é quilombo.",
                            Descricao = "Severo é nome de gente, mas também é nome de lugar. É comunidade que carrega no nome a força de quem não se curvou.",
                            Familias = "Cerca de 30 famílias",
                            Historia = "Severo é nome de gente, mas também é nome de lugar. É comunidade que carrega no nome a força de quem não se curvou. Formada nos tempos do cativeiro, essa terra foi refúgio de quem buscou liberdade e se tornou lar de quem nela se enraizou. As histórias se misturam: do tempo do engenho, da fuga, da fundação do quilombo, da luta pela terra que nunca terminou. A memória de Severo é memória de luta, mas também de fé, de festa e de muita mandinga.",
                            ImagemUrl = "assets/severo.png",
                            Municipio = "Sertânia",
                            Nome = "Severo",
                            Regiao = "Pernambuco",
                            Territorio = "O território de Severo é um corpo vivo. Cada grota, cada serra, cada nascente tem nome e história. É onde as famílias constroem suas casas, plantam seus roçados e criam seus filhos. É onde a comunidade se reúne para decidir os rumos, para celebrar e para resistir. Sem terra não tem quilombo. Em Severo, essa lição está gravada na alma de cada morador."
                        },
                        new
                        {
                            Id = 3,
                            Ano = "Origem no século XIX",
                            Codigo = 3,
                            Cultura = "A cultura de Buenos Aires é plural como sua gente. Tem o forró, tem o coco, tem a reza, tem o trabalho. É na feira, na casa de farinha, nas rodas de conversa que a cultura se reinventa. Os saberes populares são guardados com orgulho: o manejo da terra, o cuidado com os animais, o preparo dos alimentos. Aqui, ser quilombola é uma identidade assumida com orgulho, celebrada em cada gesto do cotidiano.",
                            Descricao = "Buenos Aires, em Custódia, é um quilombo que respira diversidade.",
                            Familias = "Cerca de 50 a 60 famílias",
                            Historia = "Buenos Aires, em Custódia, é um quilombo que respira diversidade. Aqui, mais de 250 famílias tecem uma história de resistência que mistura origens e saberes. Diferente de outros quilombos, Buenos Aires cresceu na confluência de culturas, sem nunca perder sua raiz negra. A terra foi conquistada a duras penas, em processos de luta que marcaram gerações. Hoje, a comunidade carrega no peito a certeza de que seu lugar é aqui, onde a história se faz coletivamente.",
                            ImagemUrl = "assets/bueno.png",
                            Municipio = "Custódia",
                            Nome = "Buenos Aires",
                            Regiao = "Pernambuco",
                            Territorio = "O território de Buenos Aires é espaço de encontro. É onde diferentes famílias constroem suas vidas em comum. É terra de criação, de plantio, de partilha. É onde a natureza e a comunidade se entrelaçam, formando um lugar único no sertão pernambucano. A defesa desse território é a defesa de um modo de vida, de uma história que não pode se perder."
                        });
                });

            modelBuilder.Entity("quilombos_api.Models.Comentario", b =>
                {
                    b.HasOne("quilombos_api.Models.Postagem", "Postagem")
                        .WithMany("Comentarios")
                        .HasForeignKey("PostagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Postagem");
                });

            modelBuilder.Entity("quilombos_api.Models.ImagemPostagem", b =>
                {
                    b.HasOne("quilombos_api.Models.Postagem", "Postagem")
                        .WithMany("Imagens")
                        .HasForeignKey("PostagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Postagem");
                });

            modelBuilder.Entity("quilombos_api.Models.Postagem", b =>
                {
                    b.HasOne("quilombos_api.Models.Quilombo", "Quilombo")
                        .WithMany("Postagens")
                        .HasForeignKey("QuilomboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quilombo");
                });

            modelBuilder.Entity("quilombos_api.Models.Postagem", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Imagens");
                });

            modelBuilder.Entity("quilombos_api.Models.Quilombo", b =>
                {
                    b.Navigation("Postagens");
                });
#pragma warning restore 612, 618
        }
    }
}
