// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using quilombos_api.Data;

#nullable disable

namespace quilombos_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("quilombos_api.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Usuario")
                        .IsUnique();

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SenhaHash = "$2a$11$SLKamRfMLdHlul5gK53UQeKH8QNkACo6zoyqlaP/JAuwNtEduqbJ2",
                            Usuario = "admin2026_quilombos"
                        });
                });

            modelBuilder.Entity("quilombos_api.Models.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PostagemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PostagemId");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("quilombos_api.Models.ImagemPostagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeOriginal")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PostagemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PostagemId");

                    b.ToTable("ImagensPostagem");
                });

            modelBuilder.Entity("quilombos_api.Models.Postagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagemHeaderPath")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuilomboId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subtitulo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuilomboId");

                    b.ToTable("Postagens");
                });

            modelBuilder.Entity("quilombos_api.Models.Quilombo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Codigo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Municipio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Regiao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Quilombos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = 1,
                            Municipio = "Sertânia",
                            Nome = "Riacho dos Porcos",
                            Regiao = "Pernambuco"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = 2,
                            Municipio = "Sertânia",
                            Nome = "Severo",
                            Regiao = "Pernambuco"
                        },
                        new
                        {
                            Id = 3,
                            Codigo = 3,
                            Municipio = "Custódia",
                            Nome = "Buenos Aires",
                            Regiao = "Pernambuco"
                        });
                });

            modelBuilder.Entity("quilombos_api.Models.Comentario", b =>
                {
                    b.HasOne("quilombos_api.Models.Postagem", "Postagem")
                        .WithMany("Comentarios")
                        .HasForeignKey("PostagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Postagem");
                });

            modelBuilder.Entity("quilombos_api.Models.ImagemPostagem", b =>
                {
                    b.HasOne("quilombos_api.Models.Postagem", "Postagem")
                        .WithMany("Imagens")
                        .HasForeignKey("PostagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Postagem");
                });

            modelBuilder.Entity("quilombos_api.Models.Postagem", b =>
                {
                    b.HasOne("quilombos_api.Models.Quilombo", "Quilombo")
                        .WithMany("Postagens")
                        .HasForeignKey("QuilomboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quilombo");
                });

            modelBuilder.Entity("quilombos_api.Models.Postagem", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Imagens");
                });

            modelBuilder.Entity("quilombos_api.Models.Quilombo", b =>
                {
                    b.Navigation("Postagens");
                });
#pragma warning restore 612, 618
        }
    }
}
