CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Admins" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Usuario" text NOT NULL,
    "SenhaHash" text NOT NULL,
    CONSTRAINT "PK_Admins" PRIMARY KEY ("Id")
);

CREATE TABLE "Quilombos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Codigo" integer NOT NULL,
    "Nome" text NOT NULL,
    "Regiao" text,
    "Municipio" text,
    CONSTRAINT "PK_Quilombos" PRIMARY KEY ("Id")
);

CREATE TABLE "Postagens" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "QuilomboId" integer NOT NULL,
    "Titulo" text NOT NULL,
    "Subtitulo" text,
    "Texto" text NOT NULL,
    "DataHora" timestamp with time zone NOT NULL,
    "ImagemHeaderPath" text,
    CONSTRAINT "PK_Postagens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Postagens_Quilombos_QuilomboId" FOREIGN KEY ("QuilomboId") REFERENCES "Quilombos" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Comentarios" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PostagemId" integer NOT NULL,
    "Nome" text NOT NULL,
    "Texto" text NOT NULL,
    "DataHora" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Comentarios" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Comentarios_Postagens_PostagemId" FOREIGN KEY ("PostagemId") REFERENCES "Postagens" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ImagensPostagem" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PostagemId" integer NOT NULL,
    "Path" text NOT NULL,
    "NomeOriginal" text,
    "Ordem" integer NOT NULL,
    CONSTRAINT "PK_ImagensPostagem" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ImagensPostagem_Postagens_PostagemId" FOREIGN KEY ("PostagemId") REFERENCES "Postagens" ("Id") ON DELETE CASCADE
);

INSERT INTO "Admins" ("Id", "SenhaHash", "Usuario")
VALUES (1, '$2a$11$d0ND.qiStwkZuqmx94n24e2XAD/wGTS/N2szk0ibvejcMwBb1nU.W', 'admin2026_quilombos');

INSERT INTO "Quilombos" ("Id", "Codigo", "Municipio", "Nome", "Regiao")
VALUES (1, 1, 'Sertânia', 'Riacho dos Porcos', 'Pernambuco');
INSERT INTO "Quilombos" ("Id", "Codigo", "Municipio", "Nome", "Regiao")
VALUES (2, 2, 'Sertânia', 'Severo', 'Pernambuco');
INSERT INTO "Quilombos" ("Id", "Codigo", "Municipio", "Nome", "Regiao")
VALUES (3, 3, 'Custódia', 'Buenos Aires', 'Pernambuco');

CREATE UNIQUE INDEX "IX_Admins_Usuario" ON "Admins" ("Usuario");

CREATE INDEX "IX_Comentarios_PostagemId" ON "Comentarios" ("PostagemId");

CREATE INDEX "IX_ImagensPostagem_PostagemId" ON "ImagensPostagem" ("PostagemId");

CREATE INDEX "IX_Postagens_QuilomboId" ON "Postagens" ("QuilomboId");

CREATE UNIQUE INDEX "IX_Quilombos_Codigo" ON "Quilombos" ("Codigo");

SELECT setval(
    pg_get_serial_sequence('"Admins"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Admins") + 1,
        nextval(pg_get_serial_sequence('"Admins"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Quilombos"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Quilombos") + 1,
        nextval(pg_get_serial_sequence('"Quilombos"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260324214132_InitialCreate', '8.0.11');

COMMIT;

